# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Terratags < Formula
  desc "A tool for validating tags on AWS resources in Terraform configurations"
  homepage "https://github.com/terratags/terratags"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/terratags/terratags/releases/download/v0.3.0/terratags_Darwin_x86_64.tar.gz"
      sha256 "8899663c4de418133a84cac1b9ae43a1f754ea7a9a0b9c876ce9316986785c14"

      def install
        bin.install "terratags"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/terratags/terratags/releases/download/v0.3.0/terratags_Darwin_arm64.tar.gz"
      sha256 "a2c44e1c4eea50a3653fa89401919b21dd6a2e5ce049623fe94e68c514f5dc76"

      def install
        bin.install "terratags"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/terratags/terratags/releases/download/v0.3.0/terratags_Linux_x86_64.tar.gz"
      sha256 "da462e63d1cf3d3be38be9ecbec89052695c29a6649cb55911252b6ba797b55c"
      def install
        bin.install "terratags"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/terratags/terratags/releases/download/v0.3.0/terratags_Linux_arm64.tar.gz"
      sha256 "75185cacebb9ee962429c96164c855974cdf64f1baa830b8cce0a446620f2a9b"
      def install
        bin.install "terratags"
      end
    end
  end

  test do
    system "#{bin}/terratags -version"
  end
end
