# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Terratags < Formula
  desc "A tool for validating tags on AWS resources in Terraform configurations"
  homepage "https://github.com/terratags/terratags"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/terratags/terratags/releases/download/v0.5.0/terratags_Darwin_x86_64.tar.gz"
      sha256 "936dea0fdd407c94b6940287a8591a39a4e56ab30a75450d387f289f2ce83ca6"

      def install
        bin.install "terratags"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/terratags/terratags/releases/download/v0.5.0/terratags_Darwin_arm64.tar.gz"
      sha256 "35057d60ca600199073511650e60c9738622eb7e35a4592904df10de868fab29"

      def install
        bin.install "terratags"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/terratags/terratags/releases/download/v0.5.0/terratags_Linux_x86_64.tar.gz"
      sha256 "d55298ab28bbe90a1748957ab1e4240ebb17d386440ae234dfc23ca98b1ce0a5"
      def install
        bin.install "terratags"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/terratags/terratags/releases/download/v0.5.0/terratags_Linux_arm64.tar.gz"
      sha256 "276c3369f990ae38db54792516097c98f1af68a8c729c1fb800bc0cf1337ce67"
      def install
        bin.install "terratags"
      end
    end
  end

  test do
    system "#{bin}/terratags -version"
  end
end
